### ISSUE TITLE
Screenshots and READMEs?

### ISSUE THREAD

**Issue by matthewwithanm** [MadkaT182/DDRNoteskins#1]
It would be awesome if each of the noteskins had a screenshot and description! I'm still not sure if there's a vivid/solo one in here! 😊

**Comment by MadkaT182** [comment]
I was thinking on the description file, at least to know the origins of every one, Initially all the noteskins are Vivid, I have the templates to create Flat, Rainbow/Solo, Note variants, I was thinking to creat a full set selectable via theming, like the original games, that's the main reason, I don want to create 3 folders of every design, but I think I will create all the note colors at least for the Normal noteskin. I will add the catalog, and the description file soon. Thanks for your comments!
